package clientews.servicio;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-10-24T11:52:11.579-06:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://servicio.sga.gm.com.mx/", name = "PersonaServiceWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonaServiceWs {

    @WebMethod
    @Action(input = "http://servicio.sga.gm.com.mx/PersonaServiceWs/listarPersonasRequest", output = "http://servicio.sga.gm.com.mx/PersonaServiceWs/listarPersonasResponse")
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ListarPersonas")
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://servicio.sga.gm.com.mx/", className = "clientews.servicio.ListarPersonasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<clientews.servicio.Persona> listarPersonas()
;
}
